Import('env')

turborav_jar = SConscript(
    "rtl/SConscript"
)

sw_env = SConscript(
    "sw/SConscript",
    exports = "env"
)

default_program = sw_env['DEFAULT_PROGRAM']
SConscript(
    "synth/SConscript",
    exports = 'turborav_jar default_program'
)

Return('turborav_jar sw_env')
