Import('turborav_jar turborav_program_env')

sim_env = DefaultEnvironment()
sim_env['CLASSPATH'] = "{}:{}".format(turborav_jar, get_classpath())
sim_env.Append(
    TURBORAV_JAR = turborav_jar,
    ENV      = {"CXX"      : "clang++"  },
    BUILDERS = {"Simulate" : sim_builder}
)

SConscript(
    "riscv/SConscript",
    exports = ' sim_env turborav_program_env'
)

SConscript(
    "c/SConscript",
    exports = 'sim_env turborav_program_env'
)

for seed in range(16) + [turborav_program_env['csmith_seed']]:
    SConscript(
        "csmith/SConscript",
        exports = 'sim_env turborav_program_env seed',
        variant_dir = "csmith/{}".format(seed)
    )

SConscript(
    "hybrid/SConscript",
    exports = 'sim_env turborav_program_env'
)

default_program = turborav_program_env['DEFAULT_PROGRAM']
SConscript(
    "unit/SConscript",
    exports = 'sim_env default_program'
)
