Import('turborav_jar riscv_program_env default_program CLASSPATH')

sim_env = DefaultEnvironment()
sim_env['CLASSPATH'] = "{}:{}".format(turborav_jar, CLASSPATH)
sim_env.Append(
    ENV      = {"CXX"      : "clang++"  },
    BUILDERS = {"Simulate" : sim_builder}
)

SConscript(
    "riscv/SConscript",
    exports = 'turborav_jar riscv_program_env sim_env'
)

SConscript(
    "unit/SConscript",
    exports = 'sim_env turborav_jar default_program'
)

SConscript(
    "c/SConscript",
    exports = 'riscv_program_env turborav_jar sim_env'
)
