Import("yosys_env blif")

yosys_env['PCF']            = File("main.pcf")
yosys_env['ASC']            = File("Soc.asc")
yosys_env['BIN']            = File("Soc.bin")
yosys_env['ICETIME_REPORT'] = File("icetime.report.txt")

yosys_env.ArachnePnr(
    yosys_env['ASC'],
    [
        yosys_env['BLIF'],
        yosys_env['PCF']
    ],
    # Bump this if the design isn't synthesizing ...
    SEED = 3
)

yosys_env.Command(
    yosys_env['BIN'],
    yosys_env['ASC'],
    "icepack $ASC $BIN"
)

yosys_env.Icetime(
    yosys_env['ICETIME_REPORT'],
    [
        yosys_env['PCF'],
        yosys_env['ASC']
    ]
)
