import os

Import('turborav_jar default_program')

synth_env = Environment(
    ENV = os.environ
)

# Verilog code generation
soc_v = synth_env.Command(
    "Soc.v",
    [turborav_jar, default_program],
    """scala \
    -classpath $turborav_jar:$CLASSPATH\
    TurboRav.TurboRav Soc $CWD $default_program 4 4""",
    turborav_jar    = turborav_jar,
    CLASSPATH       = get_classpath(),
    CWD             = Dir("."),
    default_program = default_program
)[0]

SConscript(
    "yosys/SConscript",
    exports = "soc_v"
)

# SConscript(
#     # NB: The deprecated Xilinx synthesis flow is not tested in CI and is subject
#     # to bit rot.
#     "xilinx/SConscript",
#     exports = "synth_env soc_v"
# )
