Import('turborav_program_env')

program = turborav_program_env.Program(
    [
        "btn2_to_led1.c",
        turborav_program_env["crt0_o"]
    ]
)[0]
Depends(program, turborav_program_env["LINKER_SCRIPT"])

turborav_program_env.Disassemble(str(program) + ".dis", program)

Return('program')
