from os.path import basename

Import('sim_env default_program')

sim_env['ROM'] = default_program

for scala_tb_source_path in Glob("#src/test/scala/tb/*.scala"):
    base = basename(str(scala_tb_source_path))
    top_module = base.replace("test.scala", "")
    target_dir = Dir(top_module)

    sim_env.Simulate(
        target_dir.File("jenkins.xml"),
        [sim_env["TURBORAV_JAR"], default_program],
        TARGET_DIR = target_dir,
        MODULE     = base.replace(".scala", ""),
        TOP_MODULE = top_module
    )
