import os

Import('turborav_jar CLASSPATH default_program')

synth_env = Environment(
    ENV = os.environ
)

# Verilog code generation
soc_v = synth_env.Command(
    "Soc.v",
    [turborav_jar, default_program],
    """scala \
    -classpath $turborav_jar:$CLASSPATH\
    TurboRav.TurboRav Soc $CWD $default_program 12 8 True""",
    turborav_jar    = turborav_jar,
    CLASSPATH       = CLASSPATH,
    CWD             = Dir("."),
    default_program = default_program
)[0]

SConscript(
    "xilinx/SConscript",
    exports = "synth_env soc_v"
)

SConscript(
    "yosys/SConscript",
    exports = "synth_env soc_v"
)
