lint_env = Environment()
lint_env["config"] = File("scalastyle_config.xml")

lint_env.Command(
    'main_scala_files_report.txt',
    [Glob("#build/main/scala/*"), "scalastyle_config.xml"],
    "scalastyle --config $config build/main/scala > $TARGET"
)

lint_env.Command(
    'test_scala_files_report.txt',
    [Glob("#build/test/scala/*"), "scalastyle_config.xml"],
    "scalastyle --config $config build/test/scala > $TARGET"
)
