Import('CLASSPATH')

SCALAFLAGS = ("-feature "
              "-language:reflectiveCalls "
              "-Xlint "
              "-Xfatal-warnings"
)

env = Environment()
classes = env.Command(
    '#build/scala/classes/TurboRav/TurboRav.class',
    Glob('main/scala/*') + Glob('test/scala/*'),
    "fsc {0} -classpath {1} -d build/scala/classes build/main/scala/*.scala build/test/scala/*.scala".format(
        SCALAFLAGS,
        CLASSPATH
    )
)

turborav_jar = Jar(
    target = '#build/scala/turborav.jar',
    source = Glob('#build/scala/classes/TurboRav/*')
)
Return('turborav_jar')
