from subprocess import check_output

RV32UI_PATH = "riscv-tools/riscv-tests/isa/rv32ui/"

black_list_names = [
    'amoswap_w',
    'amomaxu_w',
    'amominu_w',
    'amoadd_w',
    'amoand_w',
    'amomax_w',
    'amomin_w',
    'amoor_w',
    'fence',
    'divuw',
    'lsrc',
    'divw',
    'mulw',
    'lwu',
    'ld'
]

black_list = [
    File("{0}{1}.S".format(RV32UI_PATH, name))
    for name in black_list_names
]

test_sources = set(Glob(RV32UI_PATH + "/*.S")) - set(black_list)

CCFLAGS = ("-m32"
           " -static"
           " -nostdlib"
           " -nostartfiles"
           " -ffreestanding"
           " -Wa,-march=RVIMAFDXhwacha"
           " -Tsrc/misc/turborav.ld")

CC = '/opt/riscv/bin/riscv64-unknown-elf-gcc'

env = Environment(
    CC = CC,
    CCFLAGS = CCFLAGS,
    ASFLAGS = CCFLAGS,
    LINKFLAGS = CCFLAGS
)

CPPPATH = [
    'riscv-tools/riscv-tests/isa/macros/scalar/',
    'riscv-tools/riscv-tests/env/p'
]
programs = [ env.Program(test, CPPPATH = CPPPATH) for test in test_sources ]
Return('programs')
