import os

Import('turborav_jar CLASSPATH default_program')

synth_env = Environment(
    ENV = os.environ
)

# Verilog code generation of build/synthesis/Soc.v
soc_v = synth_env.Command(
    "Soc.v",
    [turborav_jar, default_program],
    """scala \
    -classpath {2}:{0}\
    TurboRav.TurboRav Soc build/synthesis {1} 12 8 True"""
    .format(
        CLASSPATH,
        default_program,
        turborav_jar
    )
)[0]

SConscript(
    "xilinx/SConscript",
    exports = "synth_env soc_v"
)

SConscript(
    "yosys/SConscript",
    exports = "synth_env soc_v"
)
