Import("synth_env soc_v")

cwd = Dir(".")

synth_env.Command(
    "design_routed.ncd",
    [
        soc_v,
        'Makefile',
        'turborav.ucf',
        'turborav.ut'
    ],
    'make --dir=$CWD HDL_FILE=../Soc.v design_routed.ncd',
    CWD = cwd
)
SideEffect("design_routed.par", "design_routed.ncd")

Command(
    "turborav.bit",
    "design_routed.ncd",
    'make --dir=build/synth HDL_FILE=Soc.v turborav.bit'
)

Command(
    "programming.log",
    "turborav.bit",
    'make --dir=build/synth HDL_FILE=Soc.v program'
)

Command(
    "slices.txt",
    "design_routed.par",
    "awk '/Number of Slices/{ printf \"YVALUE=%s\", $4 }' $SOURCE > $TARGET"
)
