Import('turborav_program_env sim_env')

import os

env = sim_env.Clone(
    TOP_MODULE = "Soc"
)

programs = SConscript(
    "c/SConscript",
    exports = 'turborav_program_env'
)

hybrid_tests = [
    (programs['btn2_to_led1.c'], "GpioHybridtest"      ),
    (programs['toggle_led.c']  , "GpioHybridToggletest"),
]

for test_tuple in hybrid_tests:
    program = test_tuple[0]
    module = test_tuple[1]

    target_dir = Dir("result").Dir(module).Dir(os.path.basename(str(program)))

    env.Simulate(
        target_dir.File("jenkins.xml"),
        [sim_env["TURBORAV_JAR"], program],
        TARGET_DIR = target_dir,
        ROM = program.path,
        MODULE = module
    )
